version: 2

references:
  download_build_harness: &download_build_harness
    run:
        name: Download build-harness
        command: curl --retry 5 --retry-delay 1 https://raw.githubusercontent.com/sagansystems/build-harness/master/bin/circleci.sh | bash -x -s

  go_base_container: &go_base_container
    circleci/golang:1.9

  working_directory: &working_directory
    /go/src/k8s.io/ingress-nginx

jobs:
  build:
    docker:
      - image: *go_base_container
    working_directory: *working_directory
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - *download_build_harness
      - run: make docker:login circle:cleanup-docker
      - run:
          name: Install dependencies
          command: go get github.com/golang/dep/cmd/dep
      - run:
          name: Update dependencies
          command: |
            dep ensure
            dep ensure -update
            dep prune
      - run:
          name: build nginx container locally
          command: |
            cd images/nginx
            make container
          environment:
            DOCKER: docker
            REGISTRY: sagan
      - run:
          name: Build and push the ingress-nginx container
          command: make build && make container && make push
          environment:
            # ensure linux binaries are compatible
            CGO_ENABLED: 0
            DOCKER: docker
            REGISTRY: sagan

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build

experimental:
  notify:
    branches:
      only:
        - /master/
        - /release.*/
